trigger:
  branches:
    include:
      - main

pool:
  name: Default

stages:

# =========================
# STAGE 1: SONARQUBE SCAN
# =========================
- stage: sonarscan
  displayName: SonarQube Scan
  jobs:
  - job: sonarscan
    steps:
    - task: SonarQubePrepare@5
      inputs:
        SonarQube: 'sonar-qube'
        scannerMode: 'CLI'
        configMode: 'file'

    - task: SonarQubeAnalyze@5
      inputs:
        jdkversion: 'JAVA_HOME_17_X64'

    - task: SonarQubePublish@5
      inputs:
        pollingTimeoutSec: '300'

# =========================
# STAGE 2: APPLICATION BUILD
# =========================
- stage: applicationbuild
  displayName: Application Build
  jobs:
  - job: applicationbuildjob
    steps:

    - task: NodeTool@0
      displayName: Install Node.js
      inputs:
        versionSpec: '18.x'

    # 🔑 MANDATORY: npm authentication
    - task: npmAuthenticate@0
      displayName: Authenticate npm
      inputs:
        workingFile: .npmrc

    - task: Npm@1
      displayName: npm install
      inputs:
        command: 'install'
        workingDir: '$(Build.SourcesDirectory)'

    - task: Npm@1
      displayName: npm run build
      inputs:
        command: 'custom'
        workingDir: '$(Build.SourcesDirectory)'
        customCommand: 'run build'

    - task: CopyFiles@2
      displayName: Copy build output
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)/build'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/build'

    - task: PublishBuildArtifacts@1
      displayName: Publish build artifact
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/build'
        ArtifactName: 'reactartifact'

# =========================
# STAGE 3: DEPLOYMENT
# =========================
- stage: releasestage
  displayName: Deployment Stage
  jobs:
  - job: releasejob
    steps:

    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: current
        downloadType: single
        artifactName: reactartifact
        downloadPath: '$(System.ArtifactsDirectory)'

    - task: CopyFilesOverSSH@0
      inputs:
        sshEndpoint: 'sohit-vm-ssh'
        sourceFolder: '$(System.ArtifactsDirectory)/reactartifact'
        contents: '**'
        targetFolder: '/tmp/buildartifact'

    - task: SSH@0
      inputs:
        sshEndpoint: 'sohit-vm-ssh'
        runOptions: inline
        inline: |
          sudo rm -rf /var/www/html/*
          sudo cp -r /tmp/buildartifact/* /var/www/html
